# Generated by Django 5.1.6 on 2026-04-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=200)),
                ('qualifications', models.CharField(max_length=200)),
                ('profession', models.CharField(max_length=200)),
                ('parents', models.CharField(max_length=200)),
                ('relation', models.CharField(max_length=200)),
                ('married', models.CharField(max_length=100)),
                ('languages', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
