# Generated by Django 5.2.8 on 2026-05-06 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='myapp.familymember')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('husband', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='husband_units', to='myapp.familymember')),
                ('wife', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wife_units', to='myapp.familymember')),
            ],
        ),
        migrations.AddField(
            model_name='familymember',
            name='family_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='myapp.familyunit'),
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('school', models.CharField(max_length=200)),
                ('qualifications', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=200)),
                ('relation', models.CharField(max_length=100)),
                ('spouse', models.CharField(max_length=100)),
                ('married', models.CharField(max_length=200)),
                ('languages', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_children', to='myapp.familymember')),
            ],
        ),
        migrations.AddField(
            model_name='familymember',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.register'),
        ),
    ]
