# Generated by Django 5.2.8 on 2026-05-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='spouse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
