# Generated by Django 5.2.8 on 2026-05-04 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='spouse',
        ),
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marriage_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('person1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriages_as_person1', to='myapp.familymember')),
                ('person2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriages_as_person2', to='myapp.familymember')),
            ],
        ),
    ]
