# Generated by Django 5.1.6 on 2026-05-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='dob',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='register',
            name='married',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='register',
            name='qualifications',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='relation',
            field=models.CharField(max_length=100),
        ),
    ]
