# Generated by Django 5.1.6 on 2026-05-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_register_dob_alter_register_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='spouse',
            field=models.CharField(default='01-01-2000', max_length=100),
            preserve_default=False,
        ),
    ]
