# Generated by Django 5.2.8 on 2026-05-04 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_familymember_spouse_marriage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marriage',
        ),
    ]
