# Generated by Django 5.2.8 on 2026-05-04 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_marriage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_links', to='myapp.familymember')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='myapp.familymember')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(default='spouse', max_length=20)),
                ('person1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_from', to='myapp.familymember')),
                ('person2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_to', to='myapp.familymember')),
            ],
        ),
    ]
