# Generated by Django 5.2.8 on 2026-05-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_register_address_alter_register_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='note',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
