# Generated by Django 5.2.8 on 2026-05-05 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_parentchild_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='person1',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='person2',
        ),
        migrations.DeleteModel(
            name='ParentChild',
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
