# Generated by Django 5.2.8 on 2026-05-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='is_spouse',
            field=models.BooleanField(default=False),
        ),
    ]
