# Generated by Django 5.2.8 on 2026-05-05 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_relationship_person1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_links', to='myapp.familymember')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='myapp.familymember')),
            ],
        ),
        migrations.CreateModel(
            name='Spouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_relations', to='myapp.familymember')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spouse_relations', to='myapp.familymember')),
            ],
        ),
    ]
