# Generated by Django 5.2.8 on 2026-05-05 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_parentchild_spouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('husband', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='husband_units', to='myapp.familymember')),
                ('wife', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wife_units', to='myapp.familymember')),
            ],
        ),
        migrations.AddField(
            model_name='familymember',
            name='family_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='myapp.familyunit'),
        ),
    ]
