# Generated by Django 5.2.8 on 2026-05-08 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_familymember_is_spouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='is_spouse',
        ),
    ]
