# Generated by Django 5.2.8 on 2026-06-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_familymember_is_spouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='send_notification',
            field=models.BooleanField(default=False, help_text='Tick this box to send announcement email to all members.'),
        ),
    ]
