# Generated by Django 5.2.8 on 2026-05-05 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_familyunit_familymember_family_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spouse',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='spouse',
            name='person',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='parent',
        ),
        migrations.DeleteModel(
            name='ParentChild',
        ),
        migrations.DeleteModel(
            name='Spouse',
        ),
    ]
