# Generated by Django 5.2.8 on 2026-05-05 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_spouse_partner_remove_spouse_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyunit',
            name='husband',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='husband_units', to='myapp.familymember'),
        ),
        migrations.AlterField(
            model_name='familyunit',
            name='wife',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wife_units', to='myapp.familymember'),
        ),
    ]
