# Generated by Django 5.2.8 on 2026-06-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_announcement_send_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
