# Generated by Django 5.2.8 on 2026-05-05 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_familyunit_husband_alter_familyunit_wife'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='myapp.familymember'),
        ),
    ]
